quarkus:
  mongodb:
    database: MTGames
    connection-string: mongodb://admin:adminpassword@localhost:27017/?authSource=admin

  http:
    cors: 
      origins: http://localhost:4200
      headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With,Content-Length,Accept,Origin
      methods: GET,PUT,POST,DELETE,OPTIONS
      enabled: true

cubeCobraHostName:
  mp-rest:
    url: https://cubecobra.com

devCubeOwner: adam

# Uncomment the lines below if you want to enable CORS for localhost (for development)
# quarkus:
#   http:
#     cors:
#       origins: http://localhost:4200
#       enabled: true
