quarkus:
  mongodb:
    database: MTGames
    connection-string: ${MONGO_CONNECTION:password}

  http:
    cors: 
      origins: https://pyramiddraft.xyz
      headers: Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With,Content-Length,Accept,Origin
      methods: GET,PUT,POST,DELETE,OPTIONS
      enabled: true

cubeCobraHostName:
  mp-rest:
    url: https://cubecobra.com